const { DB_URL, SECRET, TOKEN_EXPIRATION, REQUEST_TIMEOUT } = require("../config");

module.exports = {
  DB: DB_URL,
  SECRET: SECRET,
  TOKEN_EXPIRATION: TOKEN_EXPIRATION,
  REQUEST_TIMEOUT: REQUEST_TIMEOUT,
};
